export interface StateData {
  name: string
  slug: string
  kitchenRemodel: { min: number; max: number; avg: number }
  bathroomReno: { min: number; max: number; avg: number }
  deckCostPerSqFt: { min: number; max: number; avg: number }
  description: string
  cities: string[]
}

export const statesData: Record<string, StateData> = {
  alabama: {
    name: 'Alabama',
    slug: 'alabama',
    kitchenRemodel: { min: 14000, max: 58000, avg: 31000 },
    bathroomReno: { min: 5500, max: 24000, avg: 12500 },
    deckCostPerSqFt: { min: 14, max: 32, avg: 22 },
    description: 'Alabama homeowners benefit from lower labor costs compared to national averages. The state\'s hot, humid summers make deck and patio projects ideal for extending indoor living space, while kitchen and bathroom renovations consistently deliver strong ROI in this growing market.',
    cities: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery'],
  },
  alaska: {
    name: 'Alaska',
    slug: 'alaska',
    kitchenRemodel: { min: 24000, max: 95000, avg: 54000 },
    bathroomReno: { min: 9500, max: 42000, avg: 22000 },
    deckCostPerSqFt: { min: 22, max: 55, avg: 38 },
    description: 'Alaska\'s remote geography and extreme climate drive significantly higher home improvement costs. Materials must be shipped long distances, and projects must account for harsh winters and permafrost. Despite higher costs, well-executed renovations dramatically increase home values in Anchorage and Fairbanks.',
    cities: ['Anchorage', 'Fairbanks', 'Juneau'],
  },
  arizona: {
    name: 'Arizona',
    slug: 'arizona',
    kitchenRemodel: { min: 17000, max: 72000, avg: 39000 },
    bathroomReno: { min: 6500, max: 29000, avg: 15500 },
    deckCostPerSqFt: { min: 15, max: 38, avg: 26 },
    description: 'Arizona\'s booming housing market makes home improvements a smart investment. The desert climate keeps outdoor projects simpler but demands heat-resistant materials. Phoenix and Scottsdale homeowners see strong returns on kitchen upgrades, while covered patios and shade structures are perennially popular.',
    cities: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale'],
  },
  arkansas: {
    name: 'Arkansas',
    slug: 'arkansas',
    kitchenRemodel: { min: 13000, max: 54000, avg: 29000 },
    bathroomReno: { min: 5000, max: 22000, avg: 11500 },
    deckCostPerSqFt: { min: 13, max: 30, avg: 20 },
    description: 'Arkansas offers some of the lowest home improvement costs in the South. Labor is affordable and materials are accessible, making this an excellent state for DIY projects. Little Rock and Fayetteville markets are growing, boosting the ROI on strategic home renovations.',
    cities: ['Little Rock', 'Fayetteville', 'Fort Smith'],
  },
  california: {
    name: 'California',
    slug: 'california',
    kitchenRemodel: { min: 28000, max: 130000, avg: 68000 },
    bathroomReno: { min: 11000, max: 55000, avg: 28000 },
    deckCostPerSqFt: { min: 24, max: 65, avg: 44 },
    description: 'California\'s high labor costs and strict building codes make home improvement one of the most expensive in the nation. However, the state\'s sky-high home values mean renovations can add significant equity. Los Angeles, San Francisco, and San Diego homeowners typically see strong returns on quality upgrades.',
    cities: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Sacramento'],
  },
  colorado: {
    name: 'Colorado',
    slug: 'colorado',
    kitchenRemodel: { min: 22000, max: 90000, avg: 49000 },
    bathroomReno: { min: 8500, max: 38000, avg: 20000 },
    deckCostPerSqFt: { min: 19, max: 48, avg: 33 },
    description: 'Colorado\'s strong economy and rapidly appreciating real estate market make home improvements a wise investment. Denver\'s urban core and mountain communities both see demand for high-quality renovations. Deck and outdoor living projects are especially popular given the state\'s 300+ days of sunshine.',
    cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins'],
  },
  connecticut: {
    name: 'Connecticut',
    slug: 'connecticut',
    kitchenRemodel: { min: 23000, max: 95000, avg: 52000 },
    bathroomReno: { min: 9000, max: 40000, avg: 21000 },
    deckCostPerSqFt: { min: 20, max: 50, avg: 34 },
    description: 'Connecticut\'s affluent communities and New England charm drive demand for premium home renovations. Older housing stock in Hartford and Bridgeport areas often needs updating, while luxury markets in Greenwich and Westport support top-tier kitchen and bath remodels.',
    cities: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford'],
  },
  delaware: {
    name: 'Delaware',
    slug: 'delaware',
    kitchenRemodel: { min: 18000, max: 76000, avg: 42000 },
    bathroomReno: { min: 7000, max: 32000, avg: 17000 },
    deckCostPerSqFt: { min: 16, max: 42, avg: 28 },
    description: 'Delaware\'s small size and no sales tax environment make it a cost-effective state for home improvements. Wilmington\'s growing market and coastal communities in Rehoboth Beach see strong demand for renovations that blend indoor comfort with outdoor living.',
    cities: ['Wilmington', 'Dover', 'Newark'],
  },
  florida: {
    name: 'Florida',
    slug: 'florida',
    kitchenRemodel: { min: 18000, max: 82000, avg: 44000 },
    bathroomReno: { min: 7000, max: 34000, avg: 18000 },
    deckCostPerSqFt: { min: 16, max: 40, avg: 27 },
    description: 'Florida\'s year-round warm climate and booming real estate market make home improvements a constant priority. Hurricane-resistant upgrades, energy-efficient windows, and outdoor entertaining spaces are especially valuable. Miami, Orlando, and Tampa homeowners consistently see strong returns on strategic renovations.',
    cities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg'],
  },
  georgia: {
    name: 'Georgia',
    slug: 'georgia',
    kitchenRemodel: { min: 16000, max: 70000, avg: 38000 },
    bathroomReno: { min: 6200, max: 29000, avg: 15800 },
    deckCostPerSqFt: { min: 15, max: 37, avg: 25 },
    description: 'Georgia\'s thriving economy, led by the Atlanta metro area, creates strong demand for home renovations. The mild climate supports year-round outdoor projects, and the state\'s growing population keeps home values on an upward trajectory, rewarding smart improvement investments.',
    cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah'],
  },
  hawaii: {
    name: 'Hawaii',
    slug: 'hawaii',
    kitchenRemodel: { min: 32000, max: 145000, avg: 78000 },
    bathroomReno: { min: 12500, max: 62000, avg: 32000 },
    deckCostPerSqFt: { min: 28, max: 72, avg: 50 },
    description: 'Hawaii commands the highest home improvement costs in the nation due to remote island logistics and premium labor markets. Despite high upfront costs, the state\'s extraordinary home values and desirable lifestyle mean quality renovations deliver exceptional returns, especially for vacation rental properties.',
    cities: ['Honolulu', 'Hilo', 'Kailua'],
  },
  idaho: {
    name: 'Idaho',
    slug: 'idaho',
    kitchenRemodel: { min: 16000, max: 66000, avg: 36000 },
    bathroomReno: { min: 6000, max: 27000, avg: 14500 },
    deckCostPerSqFt: { min: 15, max: 36, avg: 25 },
    description: 'Idaho\'s fast-growing population, especially in the Boise area, has created a hot real estate market. Home improvement projects see strong returns as demand outpaces housing supply. The state\'s outdoor lifestyle makes deck and patio renovations particularly popular investments.',
    cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'],
  },
  illinois: {
    name: 'Illinois',
    slug: 'illinois',
    kitchenRemodel: { min: 20000, max: 88000, avg: 48000 },
    bathroomReno: { min: 7800, max: 36000, avg: 19500 },
    deckCostPerSqFt: { min: 18, max: 44, avg: 30 },
    description: 'Illinois offers a diverse home improvement market, from Chicago\'s premium urban renovations to more affordable projects in mid-sized cities. Older housing stock throughout the state provides plenty of opportunities for value-adding updates, with kitchens and bathrooms delivering the strongest ROI.',
    cities: ['Chicago', 'Aurora', 'Joliet', 'Rockford', 'Springfield'],
  },
  indiana: {
    name: 'Indiana',
    slug: 'indiana',
    kitchenRemodel: { min: 14500, max: 60000, avg: 32000 },
    bathroomReno: { min: 5500, max: 25000, avg: 13000 },
    deckCostPerSqFt: { min: 14, max: 33, avg: 22 },
    description: 'Indiana\'s affordable cost of living extends to home improvement projects. Indianapolis and Fort Wayne offer solid returns on renovations in a stabilizing market. The state\'s four distinct seasons make weather-resistant upgrades and energy-efficient improvements especially smart investments.',
    cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
  },
  iowa: {
    name: 'Iowa',
    slug: 'iowa',
    kitchenRemodel: { min: 14000, max: 58000, avg: 31500 },
    bathroomReno: { min: 5200, max: 23000, avg: 12000 },
    deckCostPerSqFt: { min: 13, max: 32, avg: 21 },
    description: 'Iowa\'s stable housing market and lower labor costs make it an ideal state for cost-effective home improvements. Des Moines has seen steady appreciation, and older homes in Cedar Rapids and Davenport offer excellent opportunities for renovation projects that deliver strong equity returns.',
    cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
  },
  kansas: {
    name: 'Kansas',
    slug: 'kansas',
    kitchenRemodel: { min: 14000, max: 58000, avg: 31000 },
    bathroomReno: { min: 5200, max: 23000, avg: 12000 },
    deckCostPerSqFt: { min: 13, max: 31, avg: 21 },
    description: 'Kansas provides affordable home improvement costs with solid returns in growing markets like Wichita and Kansas City suburbs. The state\'s central location keeps material costs reasonable, and demand for updated homes continues to grow as younger buyers enter the market.',
    cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'],
  },
  kentucky: {
    name: 'Kentucky',
    slug: 'kentucky',
    kitchenRemodel: { min: 13500, max: 56000, avg: 30000 },
    bathroomReno: { min: 5000, max: 22000, avg: 11500 },
    deckCostPerSqFt: { min: 13, max: 31, avg: 20 },
    description: 'Kentucky offers some of the most affordable home improvement costs in the nation. Louisville and Lexington markets are growing steadily, and the state\'s craftsman-style housing stock responds well to kitchen and bathroom upgrades that preserve original character while adding modern amenities.',
    cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'],
  },
  louisiana: {
    name: 'Louisiana',
    slug: 'louisiana',
    kitchenRemodel: { min: 15000, max: 63000, avg: 34000 },
    bathroomReno: { min: 5800, max: 26000, avg: 13500 },
    deckCostPerSqFt: { min: 14, max: 35, avg: 23 },
    description: 'Louisiana\'s unique architectural heritage and hot, humid climate create specific home improvement considerations. New Orleans\' historic districts require careful renovation planning, while the rest of the state benefits from moderate labor costs. Weather-resistant materials and proper moisture management are essential.',
    cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
  },
  maine: {
    name: 'Maine',
    slug: 'maine',
    kitchenRemodel: { min: 18000, max: 76000, avg: 42000 },
    bathroomReno: { min: 7000, max: 32000, avg: 17000 },
    deckCostPerSqFt: { min: 16, max: 42, avg: 28 },
    description: 'Maine\'s older housing stock and harsh winters create a steady demand for home improvements focused on energy efficiency and weatherproofing. Portland\'s competitive real estate market rewards well-executed renovations, while coastal properties benefit enormously from quality deck and porch upgrades.',
    cities: ['Portland', 'Lewiston', 'Bangor'],
  },
  maryland: {
    name: 'Maryland',
    slug: 'maryland',
    kitchenRemodel: { min: 21000, max: 88000, avg: 48000 },
    bathroomReno: { min: 8200, max: 36000, avg: 19500 },
    deckCostPerSqFt: { min: 18, max: 46, avg: 31 },
    description: 'Maryland\'s proximity to Washington D.C. and its diverse housing stock create strong demand for home improvements. Baltimore\'s revitalizing neighborhoods and D.C. suburbs both offer excellent renovation ROI. Energy-efficient upgrades and smart home technology are particularly popular with Maryland\'s tech-savvy homeowners.',
    cities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg'],
  },
  massachusetts: {
    name: 'Massachusetts',
    slug: 'massachusetts',
    kitchenRemodel: { min: 24000, max: 100000, avg: 56000 },
    bathroomReno: { min: 9500, max: 42000, avg: 22500 },
    deckCostPerSqFt: { min: 21, max: 54, avg: 37 },
    description: 'Massachusetts\' robust economy and premium housing market make it one of the higher-cost states for home improvements. Boston metro area projects command top dollar for labor, but the state\'s appreciating home values ensure strong returns. Colonial-era homes throughout the state benefit from thoughtful modernization.',
    cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
  },
  michigan: {
    name: 'Michigan',
    slug: 'michigan',
    kitchenRemodel: { min: 16000, max: 68000, avg: 37000 },
    bathroomReno: { min: 6200, max: 28000, avg: 14800 },
    deckCostPerSqFt: { min: 15, max: 37, avg: 25 },
    description: 'Michigan\'s diverse housing market ranges from Detroit\'s urban revival to affluent suburban communities and northern lake properties. Grand Rapids\' growing economy and Ann Arbor\'s university-driven demand create pockets of strong renovation ROI. Deck and waterfront improvements are especially valuable in lake country.',
    cities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
  },
  minnesota: {
    name: 'Minnesota',
    slug: 'minnesota',
    kitchenRemodel: { min: 19000, max: 80000, avg: 44000 },
    bathroomReno: { min: 7500, max: 33000, avg: 18000 },
    deckCostPerSqFt: { min: 17, max: 43, avg: 29 },
    description: 'Minnesota\'s harsh winters and lake-driven lifestyle create specific home improvement priorities. Energy efficiency upgrades, heated floors, and well-insulated renovations deliver exceptional returns. Minneapolis-St. Paul\'s strong economy supports premium kitchen and bathroom projects, while lake cabins benefit from deck and outdoor living improvements.',
    cities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth'],
  },
  mississippi: {
    name: 'Mississippi',
    slug: 'mississippi',
    kitchenRemodel: { min: 12000, max: 50000, avg: 27000 },
    bathroomReno: { min: 4500, max: 20000, avg: 10500 },
    deckCostPerSqFt: { min: 12, max: 29, avg: 19 },
    description: 'Mississippi offers the lowest home improvement costs in the nation, making it an ideal market for budget-conscious renovation projects. Jackson and Gulf Coast communities provide accessible entry points for adding significant value through kitchen and bathroom updates without breaking the bank.',
    cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg'],
  },
  missouri: {
    name: 'Missouri',
    slug: 'missouri',
    kitchenRemodel: { min: 15000, max: 63000, avg: 34000 },
    bathroomReno: { min: 5800, max: 26000, avg: 13800 },
    deckCostPerSqFt: { min: 14, max: 34, avg: 23 },
    description: 'Missouri\'s central location and affordable housing market make home improvements a smart investment. Kansas City\'s creative economy and St. Louis\'s urban renewal create demand for quality renovations. The state\'s four-season climate makes all-weather deck designs and energy-efficient upgrades particularly valuable.',
    cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
  },
  montana: {
    name: 'Montana',
    slug: 'montana',
    kitchenRemodel: { min: 18000, max: 75000, avg: 41000 },
    bathroomReno: { min: 7000, max: 32000, avg: 17000 },
    deckCostPerSqFt: { min: 17, max: 42, avg: 28 },
    description: 'Montana\'s remote wilderness lifestyle and rapidly growing real estate market (especially in Bozeman and Missoula) create unique home improvement dynamics. Rustic-chic aesthetics and mountain-modern renovations are in high demand, while durable, weather-resistant materials are essential for the state\'s harsh winters.',
    cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'],
  },
  nebraska: {
    name: 'Nebraska',
    slug: 'nebraska',
    kitchenRemodel: { min: 14000, max: 58000, avg: 31500 },
    bathroomReno: { min: 5200, max: 23000, avg: 12200 },
    deckCostPerSqFt: { min: 13, max: 31, avg: 21 },
    description: 'Nebraska\'s stable, affordable housing market makes it a solid state for home improvement investments. Omaha\'s growing tech sector is driving demand for modernized homes, while Lincoln\'s university community keeps housing demand steady. Kitchen and bathroom updates deliver reliable returns across the state.',
    cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
  },
  nevada: {
    name: 'Nevada',
    slug: 'nevada',
    kitchenRemodel: { min: 18000, max: 78000, avg: 43000 },
    bathroomReno: { min: 7000, max: 32000, avg: 17500 },
    deckCostPerSqFt: { min: 16, max: 40, avg: 27 },
    description: 'Nevada\'s desert climate and booming Las Vegas market create unique home improvement opportunities. Drought-resistant outdoor improvements, energy-efficient cooling systems, and desert-modern aesthetics are highly valued. Reno\'s growing tech economy has also sparked demand for premium home upgrades in Northern Nevada.',
    cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas'],
  },
  'new-hampshire': {
    name: 'New Hampshire',
    slug: 'new-hampshire',
    kitchenRemodel: { min: 20000, max: 84000, avg: 46000 },
    bathroomReno: { min: 7800, max: 35000, avg: 18800 },
    deckCostPerSqFt: { min: 18, max: 45, avg: 31 },
    description: 'New Hampshire\'s no income tax environment and strong New England housing market make home improvements an especially attractive investment. Manchester and Nashua\'s proximity to Boston brings premium buyers to the market, while the state\'s scenic countryside commands top dollar for well-maintained lakefront and mountain properties.',
    cities: ['Manchester', 'Nashua', 'Concord', 'Derry'],
  },
  'new-jersey': {
    name: 'New Jersey',
    slug: 'new-jersey',
    kitchenRemodel: { min: 23000, max: 96000, avg: 53000 },
    bathroomReno: { min: 9000, max: 40000, avg: 21500 },
    deckCostPerSqFt: { min: 20, max: 52, avg: 35 },
    description: 'New Jersey\'s high property values and proximity to New York City make it one of the stronger home improvement markets in the nation. Suburban communities throughout Bergen, Morris, and Monmouth counties see robust demand for kitchen and bath renovations that command significant premiums at resale.',
    cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth'],
  },
  'new-mexico': {
    name: 'New Mexico',
    slug: 'new-mexico',
    kitchenRemodel: { min: 15000, max: 64000, avg: 35000 },
    bathroomReno: { min: 5800, max: 27000, avg: 14200 },
    deckCostPerSqFt: { min: 14, max: 35, avg: 24 },
    description: 'New Mexico\'s adobe and pueblo-style architecture create unique renovation considerations. Albuquerque and Santa Fe\'s growing real estate markets reward renovations that blend Southwestern aesthetics with modern amenities. The high desert climate is ideal for covered patio and courtyard outdoor living projects.',
    cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
  },
  'new-york': {
    name: 'New York',
    slug: 'new-york',
    kitchenRemodel: { min: 26000, max: 120000, avg: 65000 },
    bathroomReno: { min: 10000, max: 52000, avg: 27000 },
    deckCostPerSqFt: { min: 22, max: 60, avg: 41 },
    description: 'New York State offers wildly variable home improvement costs, from Manhattan\'s sky-high labor rates to more affordable projects in upstate communities. NYC boroughs command premium prices but deliver exceptional returns in a market where a renovated kitchen can add six figures to a home\'s value.',
    cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'],
  },
  'north-carolina': {
    name: 'North Carolina',
    slug: 'north-carolina',
    kitchenRemodel: { min: 16000, max: 68000, avg: 37000 },
    bathroomReno: { min: 6200, max: 28000, avg: 14800 },
    deckCostPerSqFt: { min: 15, max: 37, avg: 25 },
    description: 'North Carolina\'s booming real estate market, fueled by Research Triangle and Charlotte\'s tech sector growth, makes home improvements a compelling investment. The mild four-season climate supports outdoor living projects nearly year-round, and the state\'s rapidly appreciating home values amplify renovation returns.',
    cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
  },
  'north-dakota': {
    name: 'North Dakota',
    slug: 'north-dakota',
    kitchenRemodel: { min: 15000, max: 62000, avg: 33500 },
    bathroomReno: { min: 5700, max: 25000, avg: 13200 },
    deckCostPerSqFt: { min: 14, max: 34, avg: 23 },
    description: 'North Dakota\'s oil economy has boosted home values in Williston and Bismarck, creating demand for quality renovations. The state\'s extreme winters make energy-efficient upgrades especially valuable, and there\'s strong demand for weather-tight home improvements that can withstand brutal cold.',
    cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'],
  },
  ohio: {
    name: 'Ohio',
    slug: 'ohio',
    kitchenRemodel: { min: 15500, max: 65000, avg: 35500 },
    bathroomReno: { min: 6000, max: 27000, avg: 14000 },
    deckCostPerSqFt: { min: 14, max: 35, avg: 24 },
    description: 'Ohio\'s diverse economy and affordable housing market make it a reliable state for home improvement returns. Columbus is one of the fastest-growing metros in the Midwest, driving demand for renovated properties. Cleveland and Cincinnati\'s revitalizing urban cores also present excellent renovation opportunities.',
    cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
  },
  oklahoma: {
    name: 'Oklahoma',
    slug: 'oklahoma',
    kitchenRemodel: { min: 14000, max: 58000, avg: 31000 },
    bathroomReno: { min: 5300, max: 23500, avg: 12200 },
    deckCostPerSqFt: { min: 13, max: 31, avg: 21 },
    description: 'Oklahoma offers affordable home improvement costs with solid returns in growing markets like Oklahoma City and Tulsa. Storm-resistant improvements are particularly smart investments given the state\'s tornado exposure. The state\'s oil economy historically supports strong consumer spending on home upgrades.',
    cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
  },
  oregon: {
    name: 'Oregon',
    slug: 'oregon',
    kitchenRemodel: { min: 21000, max: 88000, avg: 48000 },
    bathroomReno: { min: 8200, max: 36000, avg: 19500 },
    deckCostPerSqFt: { min: 18, max: 46, avg: 31 },
    description: 'Oregon\'s thriving tech economy and outdoor lifestyle culture drive strong demand for home improvements. Portland\'s competitive real estate market rewards premium kitchen and bath renovations, while the state\'s love of the outdoors makes covered deck and outdoor kitchen projects highly sought after.',
    cities: ['Portland', 'Eugene', 'Salem', 'Gresham'],
  },
  pennsylvania: {
    name: 'Pennsylvania',
    slug: 'pennsylvania',
    kitchenRemodel: { min: 18000, max: 78000, avg: 43000 },
    bathroomReno: { min: 7000, max: 33000, avg: 17500 },
    deckCostPerSqFt: { min: 16, max: 42, avg: 28 },
    description: 'Pennsylvania\'s vast housing market spans Philadelphia\'s premium suburbs to Pittsburgh\'s revitalized urban neighborhoods and rural communities in between. The state\'s older housing stock presents abundant renovation opportunities, and strategic upgrades deliver strong returns especially in the Pittsburgh and Philadelphia metro areas.',
    cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'],
  },
  'rhode-island': {
    name: 'Rhode Island',
    slug: 'rhode-island',
    kitchenRemodel: { min: 20000, max: 84000, avg: 46000 },
    bathroomReno: { min: 7800, max: 35000, avg: 18500 },
    deckCostPerSqFt: { min: 18, max: 46, avg: 31 },
    description: 'Rhode Island\'s small size belies a premium housing market, especially in Providence and coastal communities. Newport\'s luxury real estate and coastal cottage demand drive high renovation spending, while Providence\'s urban revival has created exciting opportunities for kitchen and bath modernization projects.',
    cities: ['Providence', 'Cranston', 'Warwick', 'Pawtucket'],
  },
  'south-carolina': {
    name: 'South Carolina',
    slug: 'south-carolina',
    kitchenRemodel: { min: 15000, max: 64000, avg: 35000 },
    bathroomReno: { min: 5800, max: 26500, avg: 14000 },
    deckCostPerSqFt: { min: 14, max: 36, avg: 24 },
    description: 'South Carolina\'s growing coastal communities and inland markets offer excellent home improvement opportunities. Charleston\'s historic homes reward careful, character-preserving renovations, while Greenville\'s growing economy drives demand for modern kitchen and bath upgrades that help properties stand out in competitive markets.',
    cities: ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant'],
  },
  'south-dakota': {
    name: 'South Dakota',
    slug: 'south-dakota',
    kitchenRemodel: { min: 14500, max: 60000, avg: 32000 },
    bathroomReno: { min: 5500, max: 24500, avg: 12800 },
    deckCostPerSqFt: { min: 14, max: 33, avg: 22 },
    description: 'South Dakota\'s no income tax and low cost of living make it an attractive market for home improvements. Sioux Falls\' growing economy is one of the fastest-growing in the region, and rapid population growth means renovated homes attract premium buyers. Outdoor improvements must account for harsh winters.',
    cities: ['Sioux Falls', 'Rapid City', 'Aberdeen'],
  },
  tennessee: {
    name: 'Tennessee',
    slug: 'tennessee',
    kitchenRemodel: { min: 15500, max: 66000, avg: 36000 },
    bathroomReno: { min: 6000, max: 27500, avg: 14500 },
    deckCostPerSqFt: { min: 14, max: 36, avg: 24 },
    description: 'Tennessee\'s no income tax environment and booming real estate market make home improvements an especially attractive investment. Nashville\'s explosive growth and Memphis\'s urban revival create strong demand for renovated properties. The mild climate supports outdoor living projects for most of the year.',
    cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
  },
  texas: {
    name: 'Texas',
    slug: 'texas',
    kitchenRemodel: { min: 17000, max: 74000, avg: 40000 },
    bathroomReno: { min: 6500, max: 30000, avg: 16000 },
    deckCostPerSqFt: { min: 15, max: 38, avg: 26 },
    description: 'Texas\' massive and diverse real estate market makes home improvements a compelling investment. No state income tax, strong job growth in Austin, Dallas, and Houston, and rapidly appreciating property values create ideal conditions for renovation ROI. The warm climate makes outdoor living spaces especially valuable year-round.',
    cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso'],
  },
  utah: {
    name: 'Utah',
    slug: 'utah',
    kitchenRemodel: { min: 19000, max: 80000, avg: 44000 },
    bathroomReno: { min: 7400, max: 33000, avg: 18000 },
    deckCostPerSqFt: { min: 17, max: 43, avg: 29 },
    description: 'Utah\'s rapidly growing population and strong economy make it one of the hottest home improvement markets in the West. Salt Lake City\'s tech sector and ski resort communities both drive demand for premium renovations. The state\'s outdoor culture makes deck and patio projects especially popular investments.',
    cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan'],
  },
  vermont: {
    name: 'Vermont',
    slug: 'vermont',
    kitchenRemodel: { min: 19000, max: 80000, avg: 44000 },
    bathroomReno: { min: 7500, max: 33000, avg: 17800 },
    deckCostPerSqFt: { min: 18, max: 44, avg: 30 },
    description: 'Vermont\'s scenic beauty and small-town charm command premium prices for well-maintained homes. Burlington\'s growing tech scene and ski country vacation properties both benefit from quality renovations. Energy-efficient upgrades are particularly valuable given the state\'s harsh winters and eco-conscious homeowners.',
    cities: ['Burlington', 'South Burlington', 'Rutland', 'Montpelier'],
  },
  virginia: {
    name: 'Virginia',
    slug: 'virginia',
    kitchenRemodel: { min: 20000, max: 85000, avg: 47000 },
    bathroomReno: { min: 7800, max: 35000, avg: 18800 },
    deckCostPerSqFt: { min: 18, max: 45, avg: 30 },
    description: 'Virginia\'s proximity to Washington D.C. and its diverse economy create a robust home improvement market. Northern Virginia commands premium prices and renovation costs, while Richmond and Virginia Beach offer more accessible markets with solid returns. The state\'s mild climate supports year-round outdoor improvement projects.',
    cities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington'],
  },
  washington: {
    name: 'Washington',
    slug: 'washington',
    kitchenRemodel: { min: 23000, max: 96000, avg: 53000 },
    bathroomReno: { min: 9000, max: 40000, avg: 21500 },
    deckCostPerSqFt: { min: 20, max: 52, avg: 35 },
    description: 'Washington State\'s tech economy, led by Seattle\'s Amazon and Microsoft presence, drives one of the nation\'s strongest home improvement markets. No state income tax and premium home values mean renovations deliver exceptional returns. The Pacific Northwest lifestyle makes indoor-outdoor living projects particularly valued.',
    cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  },
  'west-virginia': {
    name: 'West Virginia',
    slug: 'west-virginia',
    kitchenRemodel: { min: 12000, max: 50000, avg: 27000 },
    bathroomReno: { min: 4500, max: 20000, avg: 10500 },
    deckCostPerSqFt: { min: 12, max: 29, avg: 19 },
    description: 'West Virginia offers some of the most affordable home improvement costs in the nation. While the housing market is smaller, strategic renovations in growing areas like Charleston and Morgantown can deliver strong returns. The state\'s scenic mountains make exterior improvements and deck projects especially appealing.',
    cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
  },
  wisconsin: {
    name: 'Wisconsin',
    slug: 'wisconsin',
    kitchenRemodel: { min: 17000, max: 70000, avg: 38500 },
    bathroomReno: { min: 6500, max: 29000, avg: 15500 },
    deckCostPerSqFt: { min: 16, max: 38, avg: 26 },
    description: 'Wisconsin\'s four-season climate and strong Midwest work ethic create excellent conditions for home improvement projects. Milwaukee\'s revitalized neighborhoods and Madison\'s university-driven housing demand both reward well-executed renovations. The state\'s lake culture makes waterfront deck and patio projects especially valuable.',
    cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'],
  },
  wyoming: {
    name: 'Wyoming',
    slug: 'wyoming',
    kitchenRemodel: { min: 17000, max: 70000, avg: 38000 },
    bathroomReno: { min: 6500, max: 29000, avg: 15500 },
    deckCostPerSqFt: { min: 16, max: 40, avg: 27 },
    description: 'Wyoming\'s no income tax and wide-open spaces attract remote workers and retirees seeking quality homes. Jackson Hole commands luxury renovation prices, while Cheyenne and Casper offer more moderate markets. The state\'s dramatic weather swings make high-quality, durable improvements especially important for long-term value.',
    cities: ['Cheyenne', 'Casper', 'Laramie', 'Jackson'],
  },
}

export const allStateSlugs = Object.keys(statesData)
